### PR TITLE
add raw accessor

### PR DESCRIPTION
**Pull request by andyburke**

### CODE REVIEW

**Comment by andyburke** [comment]
I closed my other PR in preference to this. Once this is integrated and released, I'll push a ksuid-cli based on what I submitted in the other one.

Let me know if there's anything missing from this PR.

**Comment by novemberborn** [comment]
Thank! Out as `1.1.0`. Happy to link to your project when it's ready 👍

**Comment by andyburke** [comment]
Thanks!

https://www.npmjs.com/package/ksuid-cli

**Comment by novemberborn** [comment]
@andyburke awesome. I've pushed a link in this package's README as well: https://www.npmjs.com/package/ksuid

**Pull request merged**
